config/routes.rb
Rails.application.routes.draw do
  root 'game#new'
  get 'game/win'
  get 'game/lose'
  get 'game/show'
  get 'game/new'
  post 'game/create'
  post 'game/guess'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word_game.rb
class WordGame

  # Author: Mark Smucker
  # Date: June 2020

  attr_reader :word, :guesses, :wrong_guesses
    
  def initialize(word, availguesses)
    @word = word.downcase
    @guesses = '' # stores all correct guesses
    @wrong_guesses = '' # stores all incorrect guesses
    @availguesses = availguesses
  end  
  
  # returns true if illegal argument for guess method
  # use this to check argument and avoid exception
  def guess_illegal_argument? letter
    letter == nil || letter.length != 1 || letter =~ /[^a-zA-Z]/
  end
  
  def availguesses
      return @availguesses
  end
    
  # user guesses this letter
  # return true if not guessed before
  # return false if guessed
  # @guesses is a string holding all unique guesses
  # WordGame is case insensitive, change all guesses to lowercase via downcase
  def guess letter
     if guess_illegal_argument? letter
         raise ArgumentError, 'letter must be a single character a-zA-Z'
     end
      
     letter = letter.downcase
     if @word.include? letter
        if ! @guesses.include? letter 
           @guesses << letter
           return true 
        else
           return false
        end
     else
        if ! @wrong_guesses.include? letter
            @wrong_guesses << letter
            return true
        else
            return false
        end
     end
  end
    
  def check_win_or_lose
      if @wrong_guesses.length >= @availguesses
         return :lose
      elsif word_with_guesses == @word 
         return :win
      else
         return :play
      end
  end
    
  def word_with_guesses
     if @guesses == ''
        return @word.gsub /./, '-'
     else
        return @word.gsub /[^#{@guesses}]/, '-'     
     end
  end

  # Get a word from remote "random word" service
  #     
  # You can test get_random_word by running $ bundle exec irb -I. -r app.rb
  # And then in the irb: irb(main):001:0> WordGame.get_random_word
  #  => "cooking"   <-- some random word
  def self.get_random_word
    require 'uri'
    require 'net/http'
    uri = URI('http://watchout4snakes.com/wo4snakes/Random/RandomWord')
    Net::HTTP.new('watchout4snakes.com').start { |http|
      return http.post(uri, "").body
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
    
  def store_game_in_session
    session[:game] = @game.to_yaml
  end  
    
  def get_game_from_session
    if !session[:game].blank? 
      @game = YAML.load(session[:game])
    else
      @game = WordGame.new('', 0)
    end
  end
    
  before_action :get_game_from_session
  after_action :store_game_in_session
    
  def win
      if @game.word_with_guesses != @game.word
          redirect_to game_show_path
      end
  end

  def lose
      if @game.wrong_guesses.length < @game.availguesses.to_i
          redirect_to game_show_path
      end
  end

  def show
  end

  def new
  end

  def create
      word = params[:word] || WordGame.get_random_word
      num = params[:availguesses].to_s[0]
      if num.match? /\A[a-zA-Z'-]*\z/
          flash[:message] = "You must enter a number zero or larger!"
          redirect_to game_new_path
      else
          num = params[:availguesses].to_i
          if num<0 || num==nil
              flash[:message] = "You must enter a number zero or larger!"
              redirect_to game_new_path
          else
              @game = WordGame.new(word, num)
              redirect_to game_show_path
          end
      end
  end

  def guess
    letter = params[:guess].to_s[0]
    
    if @game.guess_illegal_argument? letter
        flash[:message] = "Invalid guess."
    elsif ! @game.guess letter # enter the guess here
        flash[:message] = "You have already used that letter."
    end
    
    if @game.check_win_or_lose == :win
        redirect_to game_win_path
    elsif @game.check_win_or_lose == :lose
        redirect_to game_lose_path
    else    
        redirect_to game_show_path
    end
  end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/create.html.erb
<h1>Game#create</h1>
<p>Find me in app/views/game/create.html.erb</p>

app/views/game/guess.html.erb
<h1>Game#guess</h1>
<p>Find me in app/views/game/guess.html.erb</p>

app/views/game/lose.html.erb
<p>Sorry, you lose!</p>
<p>The word was "<%= @game.word %>".</p>
<%= render template: 'game/new' %>

app/views/game/new.html.erb
<%= form_with( url: game_create_path, local: true) do |form| %>
<%= label_tag("Enter max allowable number of guesses:") %>
<%= text_field_tag( :availguesses, placeholder="7") %>
<% if flash[:message] %>
  <p><%= flash[:message] %></p>
<% end %>
<%= submit_tag 'New Game' %>
<% end %>

app/views/game/show.html.erb
<% if flash[:message] %>
  <p><%= flash[:message] %></p>
<% end %>
<p>You have <%= @game.availguesses-@game.wrong_guesses.length %> guesses remaining.</p>
<p>Wrong guesses: <%= @game.wrong_guesses %></p>
<p>Word so far: <%= @game.word_with_guesses %></p>
<p>
<%= form_with( url: game_guess_path, local: true) do |form| %>
<%= label_tag( :guess, "Guess a letter:" ) %>
<%= text_field_tag( :guess, nil, maxlength: 1 ) %>
<%= submit_tag 'Guess!' %>
<% end %>
</p>
<%= render template: 'game/new' %>

app/views/game/win.html.erb
<p>You Win!</p>
<p>The word was "<%= @game.word %>".</p>
<%= render template: 'game/new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wordgame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <h1>Suvaena Laventhiran's WordGame</h1>
    <%= yield %>
  </body>
</html>